site_name: Illegitimate Humans
site_description: A Wiki-style documentation site
site_author: Montreal L. Barrett
site_url: https://www.illegitimatehumans.com

theme:
  logo: assets/logo.png
  favicon: assets/favicon.ico

  name: material
  palette:
    scheme: default      # light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.expand
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - Plex:
      - Overview: plex/index.md
      - Getting Started: plex/getting-started.md
      - Clients: plex/clients.md
      - Transcoding: plex/transcoding.md
      - Server Setup: plex/server-setup.md
      - Mobile Apps: plex/mobile.md
      - Tips & Tricks: plex/tips.md
      - FAQ: plex/faq.md
      - Resources: plex/resources.md
